sonar.projectKey=music-recommendation-system
sonar.projectName=music-recommendation-system
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=notebooks/**,artifacts/**,.venv/**,data/**
sonar.test.inclusions=tests/**
